modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="cheaters"
version="1.0.0"
displayName="Cheater Mod"
displayURL="https://mcreator.net"
credits="MCreater for the modmaker"
authors="ljber"
description="A nice mod that \"helps\" you win in PVP. And can destroy a Warden in a single hit."

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.cheaters]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.137,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.cheaters]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration